apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaletest-deployment
  labels:
    app: scaletest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaletest
  template:
    metadata:
      labels:
        app: scaletest
    spec:
      containers:
        - name: scaletest-container
          image: shestera/scaletestapp:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "30Mi"
            requests:
              memory: "20Mi"
