apiVersion: v1
kind: Service
metadata:
  name: scaletest-service
spec:
  type: LoadBalancer
  selector:
    app: scaletest
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32222